services:
  db:
    image: mysql:8.4
    container_name: db
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: django
      MYSQL_PASSWORD: django123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
      - ./media:/app/media
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEBUG: "1"
      DB_NAME: bancolapsid
      DB_USER: django
      DB_PASSWORD: django123
      DB_HOST: db
      DB_PORT: 3306
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
