import type { Metadata } from "next";
import "../app/globals.css";
import { AuthProvider } from './context/Auth';
import { RouteGuard } from './middleware/RouteGuard';

import Header from "./Components/Header";
import Footer from "./Components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR"  style={{ margin: "0 auto", padding: "0 auto", height: "100%"}}>
      <body style={{ margin: "0 auto", padding: "0 auto", height: "100%"}}>
        <AuthProvider>
          <RouteGuard>
            <Header/>
              {children}
            <Footer/>
          </RouteGuard>
        </AuthProvider>
      </body>
    </html>
  );
}
