# Generated by Django 5.1.7 on 2025-05-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_usuarios_last_login_usuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(default='1234', max_length=128),
        ),
    ]
