# Generated by Django 5.1.7 on 2025-05-26 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_usuarios_groups_usuarios_is_active_usuarios_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='senha',
        ),
    ]
