# Generated by Django 5.1.7 on 2025-06-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0007_remove_usuarios_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcerias',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='parcerias/'),
        ),
    ]
