# Generated by Django 5.1.7 on 2025-06-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0008_alter_parcerias_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcerias',
            name='imagem',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='parcerias/'),
        ),
    ]
