# Generated by Django 5.1.7 on 2025-06-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0009_alter_parcerias_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcerias',
            name='link',
        ),
    ]
