# Generated by Django 5.1.7 on 2025-06-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0010_remove_parcerias_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacoes',
            name='autor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
