# Generated by Django 5.1.7 on 2025-06-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0011_alter_publicacoes_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='autor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
