# Generated by Django 5.1.7 on 2025-08-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0012_projetos_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='projetos/'),
        ),
    ]
