# Generated by Django 5.1.7 on 2025-08-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0013_projetos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='imagem',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='projetos/'),
        ),
    ]
